[project]
name = "article-relevance-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.0",
    "pyalex>=0.15.1",
    "requests>=2.32.3",
]
